@isTest(SeeAllData = false)
public class ExamenLiliTest {
/*
    @testSetup
    
    static void setup() {
        Profile profileAdmin = [SELECT Id FROM Profile WHERE Name = 'Administrador del sistema'];
        UseRole roleAdmin = [SELECT Id FROM UserRole WHERE PortalType = 'None' LIMIT 1];
        User user_test = new User(UserRoleId = roleAdmin.Id, ProfileId = profileAdmin.Id,
                                 Username = 'contactAdmin@nissan.com', Alias = 'Admin',
                                 Email = '')
    }*/
}